[package]
name = "rtcp"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.29.1", features = ["io-util", "io-std", "macros", "net", "rt-multi-thread", "time"] }
env_logger = "0.10.0"
log = "0.4.19"